### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by seaniedan** [xychelsea/deepfacelab-docker#7]
Hi Chelsea, and apologies if I have misunderstood everything but... I was looking for a way to run the DeepFaceLab repo in Docker, started coding my own, figured out I'd better have a look around first, and chanced upon your Docker images.

I now realise you have a [Twitch stream with 15.2K subscribers](https://www.twitch.tv/xychelsea87) - amazing! Very entertaining and worth a watch. So I don't know if this repo is even meant to be used, but in the spirit of trying to assist, I respectfully present my latest finding!

I was trying to launch script 4.2_data_src_sort.sh :

```
(deepfacelab) anaconda@aaab3d68ee7e:~/scripts$ ./4.2_data_src_sort.sh 
Traceback (most recent call last):
  File "/usr/local/deepfacelab/main.py", line 324, in <module>
    arguments.func(arguments)
  File "/usr/local/deepfacelab/main.py", line 68, in process_sort
    from mainscripts import Sorter
  File "/usr/local/deepfacelab/mainscripts/Sorter.py", line 14, in <module>
    from core import imagelib, mathlib, pathex
  File "/usr/local/deepfacelab/core/imagelib/__init__.py", line 5, in <module>
    from .text import get_text_image, get_draw_text_lines
  File "/usr/local/deepfacelab/core/imagelib/text.py", line 3, in <module>
    from PIL import Image, ImageDraw, ImageFont
ModuleNotFoundError: No module named 'PIL'
```
I'm going to try and debug, and if I find a solution, would a pull request be useful to you? I imagine you could solve this a lot faster than me!

**Comment by seaniedan** [comment]
In the meantime, this error can be fixed by adding the line
        pillow \
in the dockerfile after the line 
RUN conda create -c conda-forge -n deepfacelab \

Will attempt a pull request shortly.
